# Generated by Django 5.1.3 on 2025-02-12 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
