# Generated by Django 5.1.3 on 2025-02-13 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0003_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
