# Generated by Django 5.1.3 on 2025-02-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackusers', '0004_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
