# Generated by Django 5.1.3 on 2025-02-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackusers', '0005_remove_profile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
    ]
